apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170348208
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170348208
    app.kubernetes.io/part-of: test-app-170348208
  name: java-quarkus-170348208
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170348208
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170348208
    spec:
      containers:
      - image: quay.io/hacdev/0frux1pv-tenant/test-app-170348208/java-quarkus-170348208@sha256:64721c12a7bf3859deb85976f2cbfd830a799f338c127fc28ac665b00551e148
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
